//SPDX-License-Identifier: MIT
pragma solidity ^0.8.4;

// mock IExtended interface generated by ExtendLogic-getFullInterface function
interface IExtended {
    // from ExtendLogic interface
    function extend(address extension) external;
    function getFullInterface() external returns(string memory);
    function getExtensions() external returns(address[] memory);

    // from PermissioningLogic interface
    function init() external;
    function updateOwner(address newOwner) external;
    function getOwner() external returns(address);

    // from IssueLogic interface
    function issue() external;
    function issueTo(address recipient) external;

    // from RevokeLogic interface
    function revoke(address recipient) external;

    // fake function that is not implemented by the target contract and should fail when called with ExtensionNotImplemented error
    function expire() external;
}