//SPDX-License-Identifier: LGPL-3.0
pragma solidity ^0.8.4;

import "hardhat/console.sol";
import "../extensions/permissioning/PermissioningLogic.sol";

// generated by extended contract
interface IExtended {
    // from ExtendLogic interface
    function extend(address extension) external;
    function getCurrentInterface() external returns(string memory);
    function getExtensions() external returns(address[] memory);

    // from PermissioningLogic interface
    function init() external;
    function updateOwner(address newOwner) external;
    function getOwner() external returns(address);

    // from IssueLogic interface
    function issue() external;
    function issueTo(address recipient) external;

    // from RevokeLogic interface
    function revoke(address recipient) external;

    function expire() external; // fake function that is not implemented by the target contract and should fail when called with "not implemented"
}

contract CredentialCaller {
    IExtended internal target;

    constructor(address _target) {
        target = IExtended(_target);
    }

    function callExtend(address extension) public {
        target.extend(extension);
    }

    function getCurrentInterface() public returns(string memory) {
        return target.getCurrentInterface();
    }

    function getExtensions() public returns(address[] memory) {
        return target.getExtensions();
    }

    function updateOwner(address newOwner) public {
        target.updateOwner(newOwner);
    }

    function getOwner() public returns(address) {
        return target.getOwner();
    }

    function callIssue() public {
        target.issue();
    }

    function callIssueTo(address recipient) public {
        target.issueTo(recipient);
    }

    function callRevoke(address recipient) public {
        target.revoke(recipient);
    }

    function callExpire() public {
        target.expire();
    }
}

contract ExtendCaller {
    address internal _extendLogic;

    constructor(address permissioninglogic, address extendLogic) {
        (bool success, ) = permissioninglogic.delegatecall(abi.encodeWithSignature("init()"));
        require(success);
        _extendLogic = extendLogic;
    }

    function getOwner(address permissioninglogic) public returns(address owner) {
        (bool success, bytes memory result) = permissioninglogic.delegatecall(abi.encodeWithSignature("getOwner()"));
        require(success);
        owner = abi.decode(result, (address));
        return(owner);
    }

    function callExtend(address extension) public {
        (bool success, ) = _extendLogic.delegatecall(abi.encodeWithSignature("extend(address)", extension));
        require(success);
    }

    function getCurrentInterface() public returns(string memory) {
        (bool success, bytes memory result) = _extendLogic.delegatecall(abi.encodeWithSignature("getCurrentInterface()"));
        require(success);
        string memory interfaceString = abi.decode(result, (string));
        return(interfaceString);
    }

    function getExtensions() public returns(bytes4[] memory) {
        (bool success, bytes memory result) = _extendLogic.delegatecall(abi.encodeWithSignature("getExtensions()"));
        require(success);
        bytes4[] memory extensions = abi.decode(result, (bytes4[]));
        return(extensions);
    }

    function getExtensionAddresses() public returns(address[] memory) {
        (bool success, bytes memory result) = _extendLogic.delegatecall(abi.encodeWithSignature("getExtensionAddresses()"));
        require(success);
        address[] memory extensions = abi.decode(result, (address[]));
        return(extensions);
    }
}

contract RetractCaller is ExtendCaller {
    address internal _retractLogic;

    constructor(address permissioninglogic, address extendLogic, address retractLogic) ExtendCaller(permissioninglogic, extendLogic) {
        _retractLogic = retractLogic;
    }

    function callRetract(address extension) public {
        (bool success, ) = _retractLogic.delegatecall(abi.encodeWithSignature("retract(address)", extension));
        require(success);
    }
}

contract ReplaceCaller is RetractCaller {
    address internal _replaceLogic;

    constructor(address permissioninglogic, address extendLogic, address retractLogic, address replaceLogic) RetractCaller(permissioninglogic, extendLogic, retractLogic) {
        _replaceLogic = replaceLogic;
    }

    function callReplace(address oldExtension, address newExtension) public {
        (bool success, ) = _replaceLogic.delegatecall(abi.encodeWithSignature("replace(address,address)", oldExtension, newExtension));
        require(success);
    }

    // These are called by the delegatee back to self and simulates the respective extension logic
    
    function extend(address extension) public {
        callExtend(extension);
    }

    function retract(address extension) public {
        callRetract(extension);
    }
}